# Generated by Django 3.2.6 on 2021-08-17 07:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asynccalculatormodel',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asynccalculatormodel',
            name='input_data',
            field=models.JSONField(default=dict, encoder=core.models.CustomDatetimeJSONEncoder),
        ),
        migrations.AlterField(
            model_name='asynccalculatormodel',
            name='output_data',
            field=models.JSONField(default=dict, encoder=core.models.CustomDatetimeJSONEncoder),
        ),
        migrations.AlterField(
            model_name='simplecalculatormodel',
            name='input_data',
            field=models.JSONField(default=dict, encoder=core.models.CustomDatetimeJSONEncoder),
        ),
        migrations.AlterField(
            model_name='simplecalculatormodel',
            name='output_data',
            field=models.JSONField(default=dict, encoder=core.models.CustomDatetimeJSONEncoder),
        ),
        migrations.AlterField(
            model_name='wellproductionmodel',
            name='input_data',
            field=models.JSONField(default=dict, encoder=core.models.CustomDatetimeJSONEncoder),
        ),
        migrations.AlterField(
            model_name='wellproductionmodel',
            name='output_data',
            field=models.JSONField(default=dict, encoder=core.models.CustomDatetimeJSONEncoder),
        ),
    ]
