# Generated by Django 3.2.6 on 2022-02-09 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vnswellmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('nsi_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Идентификатор в НСИ')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Пометка удаления')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surmane', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('inn', models.CharField(max_length=50, verbose_name='ИНН')),
                ('snils', models.CharField(max_length=50, verbose_name='СНИЛС')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Физические лица',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('nsi_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Идентификатор в НСИ')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Пометка удаления')),
                ('employee_number', models.CharField(max_length=100, verbose_name='Табельный номер')),
                ('full_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('employment_date', models.DateField(verbose_name='Дата приема на работу')),
                ('dismissal_date', models.DateField(blank=True, verbose_name='Дата увольнения')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='Код')),
                ('is_primary_workplace', models.BooleanField(default=True, verbose_name='Основное место работы')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.individual', verbose_name='Физическое лицо')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
