# Generated by Django 3.2.6 on 2022-02-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_nsidataimportstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
    ]
