# Generated by Django 3.2.6 on 2022-02-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_individual_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
    ]
