# Generated by Django 3.2.6 on 2022-02-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220210_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='inn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='snils',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='surmane',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
    ]
