# Generated by Django 3.2.6 on 2022-02-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220210_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='surmane',
            new_name='surname',
        ),
    ]
