# Generated by Django 3.2.6 on 2022-02-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_employee_employee_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
    ]
